#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Quickstart.Resource", IsApplication=true)]

namespace Quickstart
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::ThinkGeo.UI.Android.Resource.Drawable.Compass = global::Quickstart.Resource.Drawable.Compass;
			global::ThinkGeo.UI.Android.Resource.Drawable.icon_mapsuite_default256x256 = global::Quickstart.Resource.Drawable.icon_mapsuite_default256x256;
			global::ThinkGeo.UI.Android.Resource.Drawable.icon_mapsuite_default512x512 = global::Quickstart.Resource.Drawable.icon_mapsuite_default512x512;
			global::ThinkGeo.UI.Android.Resource.Drawable.icon_mapsuite_globe = global::Quickstart.Resource.Drawable.icon_mapsuite_globe;
			global::ThinkGeo.UI.Android.Resource.Drawable.icon_mapsuite_globe_Pressed = global::Quickstart.Resource.Drawable.icon_mapsuite_globe_Pressed;
			global::ThinkGeo.UI.Android.Resource.Drawable.icon_mapsuite_Minus = global::Quickstart.Resource.Drawable.icon_mapsuite_Minus;
			global::ThinkGeo.UI.Android.Resource.Drawable.icon_mapsuite_Minus_Pressed = global::Quickstart.Resource.Drawable.icon_mapsuite_Minus_Pressed;
			global::ThinkGeo.UI.Android.Resource.Drawable.icon_mapsuite_noImageTile = global::Quickstart.Resource.Drawable.icon_mapsuite_noImageTile;
			global::ThinkGeo.UI.Android.Resource.Drawable.icon_mapsuite_Plus = global::Quickstart.Resource.Drawable.icon_mapsuite_Plus;
			global::ThinkGeo.UI.Android.Resource.Drawable.icon_mapsuite_Plus_Pressed = global::Quickstart.Resource.Drawable.icon_mapsuite_Plus_Pressed;
			global::ThinkGeo.UI.Android.Resource.String.app_name = global::Quickstart.Resource.String.app_name;
			global::ThinkGeo.UI.Android.Resource.String.hello = global::Quickstart.Resource.String.hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F010000
			public const int Compass = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int Icon = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int icon_mapsuite_default256x256 = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int icon_mapsuite_default512x512 = 2130771971;
			
			// aapt resource value: 0x7F010004
			public const int icon_mapsuite_globe = 2130771972;
			
			// aapt resource value: 0x7F010005
			public const int icon_mapsuite_globe_Pressed = 2130771973;
			
			// aapt resource value: 0x7F010006
			public const int icon_mapsuite_Minus = 2130771974;
			
			// aapt resource value: 0x7F010007
			public const int icon_mapsuite_Minus_Pressed = 2130771975;
			
			// aapt resource value: 0x7F010008
			public const int icon_mapsuite_noImageTile = 2130771976;
			
			// aapt resource value: 0x7F010009
			public const int icon_mapsuite_Plus = 2130771977;
			
			// aapt resource value: 0x7F01000A
			public const int icon_mapsuite_Plus_Pressed = 2130771978;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F020000
			public const int mapView = 2130837504;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F040000
			public const int ApplicationName = 2130968576;
			
			// aapt resource value: 0x7F040002
			public const int app_name = 2130968578;
			
			// aapt resource value: 0x7F040001
			public const int Hello = 2130968577;
			
			// aapt resource value: 0x7F040003
			public const int hello = 2130968579;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
